language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    packages:
      - clang
      - gcc
      - blender

before_install:
  # install cython
  - pip install -q cython

install:
  # manually install recent blender off mirror
  - export BLENDER_VERSION=2.80
  - echo "Installing Blender ${BLENDER_VERSION}"
  - export BNAME="blender-2.80-linux-glibc217-x86_64"
  - wget "https://builder.blender.org/download/Blender2.80/${BNAME}.tar.bz2"
  - tar -xjf ${BNAME}.tar.bz2

  # set up path to use this blender
  - export PATH=${PWD}/${BNAME}:${PATH}

  # register addon
  - export BLENDER_DIR=${HOME}/.config/blender/${BLENDER_VERSION}
  - mkdir -p ${BLENDER_DIR}/scripts/addons
  - "echo \" { \\\"Copy Target\\\" : \\\"${BLENDER_DIR}/scripts/addons\\\" }\" > conf.json"
  - python setup.py build --copy

script: ./run_test.sh -b ${BNAME}/blender
